### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by mw985793** [Sebastian09-09/snicord#3]
hey i want to ask u to how to use this on windows 11 suppose i open the snicord anzi platinum folder then i see a bunch of py files but when i run the setup.py it opens cmd   what do i do next inside it or can u tell me how to set this sniper to use for anigame?

**Comment by Sebastian09-09** [comment]
its working fine i just tested it
https://media.discordapp.net/attachments/1089769845182185605/1217342496347258961/image.png?ex=6603ad8c&is=65f1388c&hm=8601ccda8b1130006f50d2963373ce6f686585ecf8de0a15f2f47a7443c57661&=&format=webp&quality=lossless

**Comment by Sebastian09-09** [comment]
just run the setup.py , and enter the details 
it will create a new folder accounts , you can run main.py then
